=== c840670792002/GitTest/SH/src/test/resources/sig_home/conf/MessageHandlingServices.dtd
<?xml version='1.0' encoding='UTF-8'?>



<!-- DTD for "xmlRule" -->



<!ELEMENT MessageHandlingServices (Handlers*,Resources+,Properties?)>

<!ELEMENT Handlers (Handler*)>

<!ELEMENT Handler  (#PCDATA)>

<!ATTLIST Handler

	  name              CDATA             #REQUIRED

	  property     	    CDATA             #IMPLIED

>

<!ELEMENT Resources (Resource*)>

<!ELEMENT Resource  (Locale*)>

<!ATTLIST Resource

	  name              CDATA             #REQUIRED

>

<!ELEMENT Properties (MaxEntriesPerUser?,Filter?)>

<!ELEMENT MaxEntriesPerUser  (#PCDATA)>

<!ELEMENT Filter  (Severity?,TraceLevel?)>

<!ELEMENT Severity  EMPTY>

<!ATTLIST Severity  

	  fatal             (yes | no)        #REQUIRED

	  error             (yes | no)        #REQUIRED

	  warning           (yes | no)        #REQUIRED

	  information       (yes | no)        #REQUIRED

	  debug             (yes | no)        #REQUIRED

>

<!ELEMENT TraceLevel  (#PCDATA) >

<!ELEMENT Locale  EMPTY>

<!ATTLIST Locale

	  language          CDATA             #REQUIRED

	  country           CDATA             #IMPLIED

	  variant           CDATA             #IMPLIED

>

=== c840670792002/GitTest/SH/target/test-classes/sig_home/conf/messageHandlingServices.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE MessageHandlingServices SYSTEM "MessageHandlingServices.dtd">
<MessageHandlingServices>
        <Handlers>
        <!--    <Handler name="CM1GeneralLogHandler" property="CM1GeneralLogHandler">amdocs.jutil.messageHandling.HandlersImpl.messageLog.MessageLogService</Handler> -->
                <Handler name="CM1GeneralLogHandler" property="CM1GeneralLogHandler">amdocs.jutil.messageHandling.HandlersImpl.messageLog.MessageLogService</Handler>
                <Handler name="GN1GeneralLogHandler" property="">amdocs.ar.general.util.ConsoleHandler</Handler>
        </Handlers>
        <Resources>
                <Resource name="CM1Error">
                        <Locale language="en"/>
                </Resource>
                <Resource name="ACMArchError">
                        <Locale language="en"/>
                </Resource>
                <Resource name="CM5Error">
                        <Locale language="en"/>
                </Resource>
                <Resource name="ARErrorMessages">
                        <Locale language="en"/>
                </Resource>
                <Resource name="ARClientMessages">
                        <Locale language="en"/>
                </Resource>
                <Resource name="GLErrorMessages">
                        <Locale language="en"/>
                </Resource>
        </Resources>
        <Properties>
                <MaxEntriesPerUser>50</MaxEntriesPerUser>
                <Filter>
                        <Severity information="yes" warning="yes" error="yes" fatal="yes" debug="yes"/>
                        <TraceLevel>1;12</TraceLevel>
                </Filter>
        </Properties>
</MessageHandlingServices>
